kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ include "service.serviceAccountName" . }}
    namespace: "{{ $.Release.Namespace }}"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - create
  - get
  - update
- apiGroups:
  - custom.io
  resources:
  - customsecrets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - list
  - patch