kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ include "service.serviceAccountName" . }}
    namespace: "{{ $.Release.Namespace }}"
subjects:
-   kind: ServiceAccount
    name: {{ include "service.serviceAccountName" . }}
    namespace: "{{ $.Release.Namespace }}"
roleRef:
    kind: ClusterRole
    name: {{ include "service.serviceAccountName" . }}
    apiGroup: rbac.authorization.k8s.io