apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customsecrets.custom.io
spec:
  group: custom.io
  names:
    kind: CustomSecret
    listKind: CustomSecretList
    plural: customsecrets
    singular: customsecret
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                  enum:
                    - ssm
                    - secret-manager
                  description: "Type of the secret, should be either 'ssm' or 'secret-manager'"
                secrets:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string